name: 'Tests: node.js 10 - 20'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@70adccb87a0cc9b369070083adbeac469929c9fe
    with:
      range: '>= 10 < 20'
      type: minors
      command: npm run tests-only

  node:
    name: node 10 - 20
    needs: [tests]
    runs-on: ubuntu-24.04
    steps:
      - run: true
